### ISSUE TITLE
Calculadora Polonesa Tarefas

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/mallocguys#1]
-Implementar pilha (inserir,retirar).
-função de resolver operadores (+,-,*,/)
-funções adicionais

**Comment by iWarhead** [comment]
Implementei a função elementos para contar quantos números tem na pilha, adicionei operações à função inicia e corrigi alguns bugs, o programa tá funcionando.

**Comment by alessonrenato** [comment]
Pilha funcionando.
